# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- issue/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: CopyFiles@2
  inputs:
    Contents: 'build/**' # Pull the build directory (React)
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: OctopusPack@4
  inputs:
    PackageId: 'NBAcompare'
    PackageFormat: 'Zip'

- task: OctopusMetadata@4
  inputs:
    OctoConnectedServiceName: 'Octopus with jira'
    Space: 'Spaces-1'
    PackageId: 'NBAcompare'
    PackageVersion: '$(Build.BuildNumber)'
    Replace: 'false'

- task: OctopusCreateRelease@4
  inputs:
    OctoConnectedServiceName: 'Octopus with jira'
    Space: 'Spaces-1'
    ProjectGroup: 'ProjectGroups-1'
    ProjectName: 'Projects-1'
    WorkItemReleaseNotes: true
    DeployToEnvironment: 'Environments-1'
    DeploymentProgress: true

- task: OctopusDeployRelease@4
  inputs:
    OctoConnectedServiceName: 'Octopus with jira'
    Space: 'Spaces-1'
    ProjectGroup: 'ProjectGroups-1'
    Project: 'Projects-1'
    ReleaseNumber: 'latest'
    Environments: 'Environments-1'
    ShowProgress: true

- task: PublishBuildArtifacts@1
  inputs: 
    pathtoPublish: $(Build.ArtifactStagingDirectory) # dist or build files
    ArtifactName: 'www' # output artifact named www